spring.application.name=EGF Book Library
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=8080
jwt.secret=EGFLibrarySecretKey2024SuperSecureKeyForJWTTokenGeneration
jwt.expiration=86400000