spring.application.name=EGF Book Library
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Server
server.port=8080

# JWT Secret
jwt.secret=EGFLibrarySecretKey2024SuperSecureKeyForJWTTokenGeneration
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:3000
